### ISSUE TITLE
Von Gitlab: Kickoff

### ISSUE THREAD

**Issue by BingeCode** [shuffle-project/asr-api#1]
# Todos/Goals

## Research

- [x] Check open-source projects that utilise and enhance Whisper (e.g. WhisperX, whisper-cpp)
- [x] Check seamless-m4t from Meta (is this a better alternative?)
- [x] Check vosk-api, vosk-server projects regarding their APIs
- [ ] Add links to other repos if you copy/follow code

### Batch transcription

- [x] REST API endpoint for audio files
- [x] Backend can transcribe audio files in a standardized format (most likely wav, single-channel, 44.1, 16000, LE)
- [x] Backend returns a json response similar to common services (e.g. word list, timestamps, confidence, metadata)

### Stream transcription

- [x] Websocket API for streaming audio
- [x] Backend can transcribe stream
- [ ] Backend returns intermediate/partial results and final response
- [x] Response is a json similar to common services (e.g. word list, timestamps, confidence, metadata)
- [ ] API is the same as vosk-api (or provide a separate endpoint that is vosk compatible)

### Optional features

- [ ] Translation: Provide an endpoint that enables text-to-text translation (Whisper has this built-in, e.g. to translate German to English)
- [ ] Text-To-Speech: Maybe experiment with seamless-m4t to provide text to speech
- [ ] Speech-To-Speech: Maybe experiment with seamless-m4t to provide speech to speech in a streaming mode

### Deployment

- [x] Backend is dockerised (including docker-compose)
- [ ] API is optimised for performance (e.g. keep models in RAM, use tiny models for real-time transcription)
- [x] Configuration is exposed as environment variables or yaml (e.g. which models are provided in RAM or on-demand, which model sizes e.g. large, tiny, ...)
- [x] Model paths are mounted as volumes

### Documentation

- [ ] Explain how to configure the backend
- [x] List API endpoints and formats
- [ ] Provide examples if helpful

### General

- Authentication is not necessary
- Security e.g. validating the input files is not necessary
- We develop agile and integrate the backend as soon as possible into our transcription software
